import {
    VerticalBox,
    HorizontalBox,
    LineEdit,
    Button,
    CheckBox,
} from "std-widgets.slint";
import { AppState } from "app_state.slint";

component Row {
    in-out property <string> label;
    in-out property <string> value;

    HorizontalBox {
        height: 40px;
        Text {
            text: root.label;
            width: 80px;
            vertical-alignment: center;
        }

        LineEdit {
            text <=> root.value;
        }
    }
}

export component ServerConfigPage {
    callback load-cfg();
    callback save-cfg();

    VerticalBox {
        padding: 0px;
        spacing: 0px;
        VerticalBox {
            spacing: -40px;
        // 标签与输入框行
        Row {
                label: "Map:";
                value <=> AppState.server-map;
            }

            Row {
                label: "Mode:";
                value <=> AppState.server-mode;
            }

            Row {
                label: "Difficulty:";
                value <=> AppState.server-difficulty;
            }

            Row {
                label: "Server Name:";
                value <=> AppState.server-name;
            }

            Row {
                label: "Region:";
                value <=> AppState.server-region;
            }

            Row {
                label: "Port:";
                value <=> AppState.server-port;
            }

            Row {
                label: "External Port:";
                value <=> AppState.server-external-port;
            }

            Row {
                label: "Backend:";
                value <=> AppState.server-backend;
            }
        }
        // 布尔选项
        HorizontalBox {
            HorizontalBox {
                Text {
                    text: "Offline Mode:";
                    width: 120px;
                    vertical-alignment: center;
                }

                CheckBox {
                    checked <=> AppState.server-offline;
                }
            }

            HorizontalBox {
                height: 30px;
                Text {
                    text: "Use DX11:";
                    width: 120px;
                    vertical-alignment: center;
                }

                CheckBox {
                    checked <=> AppState.server-dx11;
                }
            }
        }
        // 按钮
        HorizontalBox {
            height: 40px;
            spacing: 10px;
            Button {
                text: "Load Config";
                clicked => {
                    root.load-cfg();
                }
            }

            Button {
                text: "Save Config";
                clicked => {
                    root.save-cfg();
                }
            }
        }
    }

    // 辅助组件：一行标签 + 输入框

}
